language: python
python:
    - "2.7.10"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - python manage.py db init
  - pyhton manage.py db migrate
  - python manage.py db upgrade
# command to run tests
script:
 nosetests -v --with-coverage
after_success:
  - coveralls
